spring.application.name=api-gateway
server.port=8080

# =========================================================
# EUREKA
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# =========================================================
# GATEWAY DISCOVERY
# =========================================================

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# =========================================================
# PRODUCT SERVICE
# =========================================================

spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**


# =========================================================
# INVENTORY SERVICE
# =========================================================

spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory/**


# =========================================================
# RECOMMENDATION SERVICE
# =========================================================

spring.cloud.gateway.routes[2].id=recommendation-service
spring.cloud.gateway.routes[2].uri=lb://RECOMMENDATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/recommendations/**


# =========================================================
# CIRCUIT BREAKER
# =========================================================

spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=recommendationCircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/recommendations


# =========================================================
# RATE LIMITER
# =========================================================

spring.cloud.gateway.routes[2].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[1].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[2].filters[1].args.redis-rate-limiter.replenishRate=2
spring.cloud.gateway.routes[2].filters[1].args.redis-rate-limiter.burstCapacity=2



# =========================================================
# RETRY
# =========================================================

spring.cloud.gateway.routes[2].filters[2].name=Retry
spring.cloud.gateway.routes[2].filters[2].args.retries=2
spring.cloud.gateway.routes[2].filters[2].args.methods=GET
spring.cloud.gateway.routes[2].filters[2].args.series=SERVER_ERROR

# =========================================================
# CIRCUIT BREAKER CONFIGURATION
# =========================================================

resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.wait-duration-in-open-state=10s


# =========================================================
# TIMEOUT
# =========================================================

spring.cloud.gateway.httpclient.response-timeout=2s


# =========================================================
# REDIS
# =========================================================

spring.data.redis.host=localhost
spring.data.redis.port=6379


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted
management.endpoint.health.show-details=always


# =========================================================
# ZIPKIN
# =========================================================

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


# =========================================================
# LOGGING
# =========================================================

logging.level.org.springframework.cloud.gateway.filter.factory.RequestRateLimiterGatewayFilterFactory=TRACE
logging.level.org.springframework.cloud.gateway.filter.ratelimit=TRACE
logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG


# =========================================================
# CORS
# =========================================================

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true




# =========================================================
# BULKHEAD
# =========================================================

spring.cloud.gateway.routes[2].filters[3].name=Bulkhead